# Generated by Django 5.2.6 on 2025-09-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=500)),
                ('ingredients', models.TextField(max_length=1000)),
                ('instructions', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
            ],
        ),
    ]
